# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/macncheese/Desktop/University_24/Second/Microprocessors/pico-apps

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/macncheese/Desktop/University_24/Second/Microprocessors/pico-apps

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/macncheese/Desktop/University_24/Second/Microprocessors/pico-apps/CMakeFiles /Users/macncheese/Desktop/University_24/Second/Microprocessors/pico-apps//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/macncheese/Desktop/University_24/Second/Microprocessors/pico-apps/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bs2_default

# Build rule for target.
bs2_default: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bs2_default
.PHONY : bs2_default

# fast build rule for target.
bs2_default/fast:
	$(MAKE) $(MAKESILENT) -f pico-sdk/src/rp2_common/boot_stage2/CMakeFiles/bs2_default.dir/build.make pico-sdk/src/rp2_common/boot_stage2/CMakeFiles/bs2_default.dir/build
.PHONY : bs2_default/fast

#=============================================================================
# Target rules for targets named bs2_default_bin

# Build rule for target.
bs2_default_bin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bs2_default_bin
.PHONY : bs2_default_bin

# fast build rule for target.
bs2_default_bin/fast:
	$(MAKE) $(MAKESILENT) -f pico-sdk/src/rp2_common/boot_stage2/CMakeFiles/bs2_default_bin.dir/build.make pico-sdk/src/rp2_common/boot_stage2/CMakeFiles/bs2_default_bin.dir/build
.PHONY : bs2_default_bin/fast

#=============================================================================
# Target rules for targets named bs2_default_padded_checksummed_asm

# Build rule for target.
bs2_default_padded_checksummed_asm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bs2_default_padded_checksummed_asm
.PHONY : bs2_default_padded_checksummed_asm

# fast build rule for target.
bs2_default_padded_checksummed_asm/fast:
	$(MAKE) $(MAKESILENT) -f pico-sdk/src/rp2_common/boot_stage2/CMakeFiles/bs2_default_padded_checksummed_asm.dir/build.make pico-sdk/src/rp2_common/boot_stage2/CMakeFiles/bs2_default_padded_checksummed_asm.dir/build
.PHONY : bs2_default_padded_checksummed_asm/fast

#=============================================================================
# Target rules for targets named assign01

# Build rule for target.
assign01: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 assign01
.PHONY : assign01

# fast build rule for target.
assign01/fast:
	$(MAKE) $(MAKESILENT) -f assignments/assign01/CMakeFiles/assign01.dir/build.make assignments/assign01/CMakeFiles/assign01.dir/build
.PHONY : assign01/fast

#=============================================================================
# Target rules for targets named ELF2UF2Build

# Build rule for target.
ELF2UF2Build: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ELF2UF2Build
.PHONY : ELF2UF2Build

# fast build rule for target.
ELF2UF2Build/fast:
	$(MAKE) $(MAKESILENT) -f assignments/assign01/CMakeFiles/ELF2UF2Build.dir/build.make assignments/assign01/CMakeFiles/ELF2UF2Build.dir/build
.PHONY : ELF2UF2Build/fast

#=============================================================================
# Target rules for targets named assign02

# Build rule for target.
assign02: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 assign02
.PHONY : assign02

# fast build rule for target.
assign02/fast:
	$(MAKE) $(MAKESILENT) -f assignments/assign02/CMakeFiles/assign02.dir/build.make assignments/assign02/CMakeFiles/assign02.dir/build
.PHONY : assign02/fast

#=============================================================================
# Target rules for targets named blink_c

# Build rule for target.
blink_c: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 blink_c
.PHONY : blink_c

# fast build rule for target.
blink_c/fast:
	$(MAKE) $(MAKESILENT) -f examples/blink_c/CMakeFiles/blink_c.dir/build.make examples/blink_c/CMakeFiles/blink_c.dir/build
.PHONY : blink_c/fast

#=============================================================================
# Target rules for targets named hello_c

# Build rule for target.
hello_c: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hello_c
.PHONY : hello_c

# fast build rule for target.
hello_c/fast:
	$(MAKE) $(MAKESILENT) -f examples/hello_c/CMakeFiles/hello_c.dir/build.make examples/hello_c/CMakeFiles/hello_c.dir/build
.PHONY : hello_c/fast

#=============================================================================
# Target rules for targets named multi_c

# Build rule for target.
multi_c: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 multi_c
.PHONY : multi_c

# fast build rule for target.
multi_c/fast:
	$(MAKE) $(MAKESILENT) -f examples/multi_c/CMakeFiles/multi_c.dir/build.make examples/multi_c/CMakeFiles/multi_c.dir/build
.PHONY : multi_c/fast

#=============================================================================
# Target rules for targets named blink_asm

# Build rule for target.
blink_asm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 blink_asm
.PHONY : blink_asm

# fast build rule for target.
blink_asm/fast:
	$(MAKE) $(MAKESILENT) -f examples/blink_asm/CMakeFiles/blink_asm.dir/build.make examples/blink_asm/CMakeFiles/blink_asm.dir/build
.PHONY : blink_asm/fast

#=============================================================================
# Target rules for targets named ws2812_rgb

# Build rule for target.
ws2812_rgb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ws2812_rgb
.PHONY : ws2812_rgb

# fast build rule for target.
ws2812_rgb/fast:
	$(MAKE) $(MAKESILENT) -f examples/ws2812_rgb/CMakeFiles/ws2812_rgb.dir/build.make examples/ws2812_rgb/CMakeFiles/ws2812_rgb.dir/build
.PHONY : ws2812_rgb/fast

#=============================================================================
# Target rules for targets named PioasmBuild

# Build rule for target.
PioasmBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PioasmBuild
.PHONY : PioasmBuild

# fast build rule for target.
PioasmBuild/fast:
	$(MAKE) $(MAKESILENT) -f examples/ws2812_rgb/CMakeFiles/PioasmBuild.dir/build.make examples/ws2812_rgb/CMakeFiles/PioasmBuild.dir/build
.PHONY : PioasmBuild/fast

#=============================================================================
# Target rules for targets named ws2812_rgb_ws2812_pio_h

# Build rule for target.
ws2812_rgb_ws2812_pio_h: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ws2812_rgb_ws2812_pio_h
.PHONY : ws2812_rgb_ws2812_pio_h

# fast build rule for target.
ws2812_rgb_ws2812_pio_h/fast:
	$(MAKE) $(MAKESILENT) -f examples/ws2812_rgb/CMakeFiles/ws2812_rgb_ws2812_pio_h.dir/build.make examples/ws2812_rgb/CMakeFiles/ws2812_rgb_ws2812_pio_h.dir/build
.PHONY : ws2812_rgb_ws2812_pio_h/fast

#=============================================================================
# Target rules for targets named lab01

# Build rule for target.
lab01: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lab01
.PHONY : lab01

# fast build rule for target.
lab01/fast:
	$(MAKE) $(MAKESILENT) -f labs/lab01/CMakeFiles/lab01.dir/build.make labs/lab01/CMakeFiles/lab01.dir/build
.PHONY : lab01/fast

#=============================================================================
# Target rules for targets named lab02

# Build rule for target.
lab02: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lab02
.PHONY : lab02

# fast build rule for target.
lab02/fast:
	$(MAKE) $(MAKESILENT) -f labs/lab02/CMakeFiles/lab02.dir/build.make labs/lab02/CMakeFiles/lab02.dir/build
.PHONY : lab02/fast

#=============================================================================
# Target rules for targets named lab03

# Build rule for target.
lab03: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lab03
.PHONY : lab03

# fast build rule for target.
lab03/fast:
	$(MAKE) $(MAKESILENT) -f labs/lab03/CMakeFiles/lab03.dir/build.make labs/lab03/CMakeFiles/lab03.dir/build
.PHONY : lab03/fast

#=============================================================================
# Target rules for targets named lab04

# Build rule for target.
lab04: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lab04
.PHONY : lab04

# fast build rule for target.
lab04/fast:
	$(MAKE) $(MAKESILENT) -f labs/lab04/CMakeFiles/lab04.dir/build.make labs/lab04/CMakeFiles/lab04.dir/build
.PHONY : lab04/fast

#=============================================================================
# Target rules for targets named lab05

# Build rule for target.
lab05: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lab05
.PHONY : lab05

# fast build rule for target.
lab05/fast:
	$(MAKE) $(MAKESILENT) -f labs/lab05/CMakeFiles/lab05.dir/build.make labs/lab05/CMakeFiles/lab05.dir/build
.PHONY : lab05/fast

#=============================================================================
# Target rules for targets named lab06

# Build rule for target.
lab06: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lab06
.PHONY : lab06

# fast build rule for target.
lab06/fast:
	$(MAKE) $(MAKESILENT) -f labs/lab06/CMakeFiles/lab06.dir/build.make labs/lab06/CMakeFiles/lab06.dir/build
.PHONY : lab06/fast

#=============================================================================
# Target rules for targets named lab07

# Build rule for target.
lab07: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lab07
.PHONY : lab07

# fast build rule for target.
lab07/fast:
	$(MAKE) $(MAKESILENT) -f labs/lab07/CMakeFiles/lab07.dir/build.make labs/lab07/CMakeFiles/lab07.dir/build
.PHONY : lab07/fast

#=============================================================================
# Target rules for targets named lab08

# Build rule for target.
lab08: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lab08
.PHONY : lab08

# fast build rule for target.
lab08/fast:
	$(MAKE) $(MAKESILENT) -f labs/lab08/CMakeFiles/lab08.dir/build.make labs/lab08/CMakeFiles/lab08.dir/build
.PHONY : lab08/fast

#=============================================================================
# Target rules for targets named lab09

# Build rule for target.
lab09: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lab09
.PHONY : lab09

# fast build rule for target.
lab09/fast:
	$(MAKE) $(MAKESILENT) -f labs/lab09/CMakeFiles/lab09.dir/build.make labs/lab09/CMakeFiles/lab09.dir/build
.PHONY : lab09/fast

#=============================================================================
# Target rules for targets named lab10

# Build rule for target.
lab10: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lab10
.PHONY : lab10

# fast build rule for target.
lab10/fast:
	$(MAKE) $(MAKESILENT) -f labs/lab10/CMakeFiles/lab10.dir/build.make labs/lab10/CMakeFiles/lab10.dir/build
.PHONY : lab10/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ELF2UF2Build"
	@echo "... PioasmBuild"
	@echo "... bs2_default_bin"
	@echo "... bs2_default_padded_checksummed_asm"
	@echo "... ws2812_rgb_ws2812_pio_h"
	@echo "... assign01"
	@echo "... assign02"
	@echo "... blink_asm"
	@echo "... blink_c"
	@echo "... bs2_default"
	@echo "... hello_c"
	@echo "... lab01"
	@echo "... lab02"
	@echo "... lab03"
	@echo "... lab04"
	@echo "... lab05"
	@echo "... lab06"
	@echo "... lab07"
	@echo "... lab08"
	@echo "... lab09"
	@echo "... lab10"
	@echo "... multi_c"
	@echo "... ws2812_rgb"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

