#!/bin/bash

CURRENT_PTH="$(pwd)"
LAST_FLDR=$(basename "$CURRENT_PTH")
cd ~/Documents/code/c/pico-apps/build
cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
make
cp $CURRENT_PTH/../../build/assignments/$LAST_FLDR/$LAST_FLDR.uf2 /media/$USER/RPI-RP2/
cd $CURRENT_PTH
sleep 1 
screen /dev/ttyACM0 115200 
